default_platform(:mac)

platform :mac do
  desc "Run unit tests"
  lane :run_tests do
    sh "swift test --enable-code-coverage --build-path .build"
    sh "xcrun llvm-cov export -format=lcov \
    .build/debug/CoreDataStoragePackageTests.xctest/Contents/MacOS/CoreDataStoragePackageTests \
    -instr-profile .build/debug/codecov/default.profdata > coverage.lcov"
  end
end
